name = "aeroNUTics"
author = "hexagonelle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7878760fe2ee5d10855c33bc76c39cd18d9bd456c2e5e692fe67329d993cde38"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
datapack-folder = "config\\paxi\\datapacks"
