name = "aeroNUTics"
author = "hexagonelle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1665460a30326dc963ee732cb93e305e9caa755e3e6d22eee19559c7b6cfa107"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
datapack-folder = "config\\paxi\\datapacks"
