name = "aeroNUTics"
author = "hexagonelle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f86ffa3afdf85a99880de7c548ad607bf2891f848b95bb645dbc3f191f4084b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"

[options]
datapack-folder = "config\\paxi\\datapacks"
